spring.application.name=saibaba



spring.datasource.url=jdbc:mysql://localhost:3306/NewService
spring.datasource.username=root
spring.datasource.password=sanath1234567
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanathmandala391@gmail.com
spring.mail.password=xoydoqrhnsrcjzzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=sanath
spring.security.user.password={noop}1234