spring.application.name=saibaba

spring.datasource.url=jdbc:postgresql://dpg-d792cedactks73cuj4n0-a.oregon-postgres.render.com:5432/service_to3b
spring.datasource.username=service_to3b_user
spring.datasource.password=vV9316bASTc0O4CT60OXFVV09zYFdFbj
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanathmandala391@gmail.com
spring.mail.password=xoydoqrhnsrcjzzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=sanath
spring.security.user.password={noop}1234
